groups:
- name: Node Exporter metrics
  rules:   
  - alert: Node Exporter is down
    expr: up{job="node_exporter"} == 0
    for: 1m
    labels:
      severity: CRITICAL
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 1 minute.