global:
  scrape_interval:     15s 
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alertrules.yml'

scrape_configs:

  - job_name: 'node_exporter'
    file_sd_configs:
    - files:
      - '/etc/prometheus/targets.json'